version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: family-emotions-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-family_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-family_password}
      POSTGRES_DB: ${POSTGRES_DB:-family_emotions}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U family_user -d family_emotions"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: family-emotions-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: family-emotions-bot
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-family_user}:${POSTGRES_PASSWORD:-family_password}@postgres:5432/${POSTGRES_DB:-family_emotions}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic

  migrate:
    build: .
    container_name: family-emotions-migrate
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-family_user}:${POSTGRES_PASSWORD:-family_password}@postgres:5432/${POSTGRES_DB:-family_emotions}
    command: ["poetry", "run", "alembic", "upgrade", "head"]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data: