version: '3'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: family_emotions
      POSTGRES_USER: family_bot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  bot:
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: family_emotions
      POSTGRES_USER: family_bot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    command: sh -c "sleep 20 && python -m src.bot"

volumes:
  postgres_data:
  redis_data: